language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
   - $HOME/.gradle

before_script:
  - git fetch
  - git rebase

script:
  - gradle clean test check --info
